fix angle
veeenu/eldenring-practice-tool pull request #106
Opened 2024-07-17 10:41 UTC by fvlntn

seems to be working

2024-07-17 10:54 UTC, Vinjul1704 commented
Thanks, looks like it's working. Tested on current patch with crabs and the frog people (or something) in liurnia, as well as soldiers in limgrave.

Might want to change how it's displayed, so instead of "12.34myangle 56.78enemynangle" it could be "Player angle: 12.34° | Enemy angle: 56.78°", but I would say that's up to John.

2024-07-17 10:57 UTC, fvlntn commented
yeah, I didn't know about displaying, so just put that up for debug

2024-07-17 12:17 UTC, veeenu commented
Thank you so much for your contribution! 🚀🚀🚀

I will be able to do a proper review in a few days, but the calculations make sense. I was trying to avoid conditionals but most likely they are totally fine.

I think a compass like visualization would work better, but we can do that in a separate PR.

2024-07-17 12:42 UTC, fvlntn commented
I think you could avoid conditionals by using atan2 like you did and correcting the angle to be 0 at East and going anti-clockwise like in real maths. One more thing is correcting the division by position.z - z which could be zero so one more conditional to write.

2024-07-26 12:07 UTC, veeenu requested changes
Thank you so much for this! Just a minor change request so we have a clean `main`. I'll think of an appropriate viz later.

2024-07-26 12:07 UTC, veeenu commented on practice-tool/src/widgets/target.rs
> +            );
```suggestion
            ui.text(format!("{distance:>6.3}m {my_angle_display:>6.3}deg",));
```

Let's keep it like this for now, meanwhile I'm going to cook an angle visualization before merging this into a new release.

2024-07-26 12:58 UTC, veeenu approved these changes

2024-07-26 13:00 UTC, merged